<?php

return array(
	array(
		'template'      => 'default',
		'position'      => 'hand-sided',
		'dismissDelay'  => 120,
		'title'         => null,
		'titleStyle'    => null,
		'text'          => __( '👋 Hello!', 'siteleads' ),
		'textStyle'     =>
		array(
			'color'  => '#787878',
			'family' => 'Geist',
			'weight' => '400',
			'size'   => 14,
		),
		'image'         => null,
		'width'         => null,
		'bgColor'       => '#ffffff',
		'borderWidth'   => null,
		'borderColor'   => null,
		'radius'        => 5,
		'spacing'       => 10,
		'shadow'        => '1',
		'entrance'      => 'fade',
		'entranceDelay' => 0,
		'size'          => null,
	),

	array(
		'template'      => 'template-2',
		'_template'     => 'default',
		'position'      => 'hand-sided',
		'dismissDelay'  => 120,
		'title'         => null,
		'titleStyle'    => null,
		'text'          => __( "Let's connect!", 'siteleads' ),
		'textStyle'     =>
		array(
			'color'  => '#ffffff',
			'family' => 'Geist',
			'weight' => '400',
			'size'   => 14,
		),
		'image'         => null,
		'width'         => null,
		'bgColor'       => '#171717',
		'borderWidth'   => null,
		'borderColor'   => null,
		'radius'        => 5,
		'spacing'       => 14,
		'shadow'        => '1',
		'entrance'      => 'fade',
		'entranceDelay' => 0,
		'size'          => null,
	),

	array(
		'template'      => 'template-3',
		'_template'     => 'default',
		'position'      => 'hand-sided',
		'dismissDelay'  => 120,
		'title'         => null,
		'titleStyle'    => null,
		'text'          => __( "Let's connect!", 'siteleads' ),
		'textStyle'     =>
		array(
			'color'  => '#ffffff',
			'family' => 'Geist',
			'weight' => '400',
			'size'   => 14,
		),
		'image'         => null,
		'width'         => null,
		'bgColor'       => '#6F3EF0',
		'borderWidth'   => null,
		'borderColor'   => null,
		'radius'        => 5,
		'spacing'       => 14,
		'shadow'        => '1',
		'entrance'      => 'fade',
		'entranceDelay' => 0,
		'size'          => null,
	),
	array(
		'template'      => 'template-4',
		'_template'     => 'default',
		'position'      => 'hand-sided',
		'dismissDelay'  => 120,
		'title'         => null,
		'titleStyle'    => null,
		'text'          => __( 'Hi! nice to meet you!', 'siteleads' ),
		'textStyle'     =>
		array(
			'color'  => '#ffffff',
			'family' => 'Geist',
			'weight' => '400',
			'size'   => 14,
		),
		'image'         => null,
		'width'         => null,
		'bgColor'       => '#378b44',
		'borderWidth'   => null,
		'borderColor'   => null,
		'radius'        => 5,
		'spacing'       => 14,
		'shadow'        => '1',
		'entrance'      => 'fade',
		'entranceDelay' => 0,
		'size'          => null,
	),
);
